aston_front_homepage:
    path:     /
    defaults: { _controller: AstonFrontBundle:Default:index }

aston_front_hello:
    path:     /hello/{name}
    defaults: { _controller: AstonFrontBundle:Default:hello, name: "toto" }
    methods: [GET,POST]
    requirements:
        name: "[a-z]+"

# Routes comments
aston_front_about:
    path:   /about
    defaults: { _controller: AstonFrontBundle:Default:about }

aston_front_blog:
    path:   /blog
    defaults: { _controller: AstonFrontBundle:Default:blog }

aston_front_contact:
    path:   /contact
    defaults: { _controller: AstonFrontBundle:Default:contact }

# Sessions

# Ecriture
aston_front_sesswrite:
    path:   /sess/write
    defaults: { _controller: AstonFrontBundle:Default:sessionWrite }

# Lecture
aston_front_sessread:
    path:   /sess/read
    defaults: { _controller: AstonFrontBundle:Default:sessionRead }